name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    env:
      AWS_ACCESS_KEY_ID: 'foo'
      AWS_SECRET_ACCESS_KEY: dump
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
  release:
    needs: [build]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Setup Git Identify
        run: |
          git config --global user.email "samuraitruong@users.noreply.github.com"
          git config --global user.name "Release Me"

      - name: Install
        run: yarn
      - name: Build
        run: yarn build

      - name: Release
        run: |
          yarn release
          git push --follow-tags origin master && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
